spring:
  application:
    name: basic-sample

logging:
  level:
    root: info
    co.orquex.sagas: trace

orquex:
  sagas:
    spring:
      compensation:
        enabled: true # Enable compensation